-- --------------------------------------------------------
-- 1. TABLE accounts
-- --------------------------------------------------------
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_accounts_email ON accounts (email);


-- --------------------------------------------------------
-- 2. TABLE players
-- --------------------------------------------------------
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_username VARCHAR(255) NOT NULL UNIQUE,
    is_guest BOOLEAN DEFAULT FALSE,
    account_id BIGINT UNIQUE,
    player_number INT,
    score INT,
    current_token VARCHAR(255),

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_player_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
);

CREATE INDEX idx_players_username ON players (player_username);