-- --------------------------------------------------------
-- 1. TABLE accounts
-- --------------------------------------------------------
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);
CREATE INDEX idx_accounts_email ON accounts (email);

-- --------------------------------------------------------
-- 2. TABLE players
-- --------------------------------------------------------
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT UNIQUE NOT NULL,
    player_username VARCHAR(255) NOT NULL UNIQUE, -- Renommé pour éviter la confusion avec account.username
    is_guest BOOLEAN DEFAULT FALSE,
    player_number INT,
    score INT,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_player_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
);

CREATE INDEX idx_players_username ON players (player_username);