-- --------------------------------------------------------
-- 1. TABLE cards
-- --------------------------------------------------------
CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combination VARCHAR(255) NOT NULL UNIQUE,
    color VARCHAR(255) NOT NULL,
    point_lvl1 INT NOT NULL,
    point_lvl2 INT NOT NULL,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_cards_combination ON cards (combination);