-- --------------------------------------------------------
-- 1. TABLE dice_sets
-- --------------------------------------------------------
CREATE TABLE dice_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);


-- --------------------------------------------------------
-- 2. TABLE dices
-- --------------------------------------------------------
CREATE TABLE dices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value INT NOT NULL,
    is_kept BOOLEAN NOT NULL DEFAULT FALSE,
    dice_set_id BIGINT NOT NULL,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_dice_set_id
        FOREIGN KEY (dice_set_id)
        REFERENCES dice_sets (id)
        ON DELETE CASCADE
);