-- --------------------------------------------------------
-- 1. TABLE boards
-- --------------------------------------------------------
CREATE TABLE boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT UNIQUE,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);


-- --------------------------------------------------------
-- 2. TABLE games
-- --------------------------------------------------------
CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state VARCHAR(50) NOT NULL DEFAULT 'IN_PROGRESS',
    rolls_left  INT NOT NULL DEFAULT 3,
    round_number INT NOT NULL DEFAULT 1,
    current_player_id BIGINT,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_game_current_player
       FOREIGN KEY (current_player_id)
           REFERENCES players (id)
           ON DELETE SET NULL
);


-- --------------------------------------------------------
-- 3. UPDATE EXISTING TABLES
-- --------------------------------------------------------

-- boards
ALTER TABLE boards
    ADD CONSTRAINT fk_board_game
        FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE;

-- dice_sets
ALTER TABLE dice_sets ADD COLUMN game_id BIGINT UNIQUE;

ALTER TABLE dice_sets
    ADD CONSTRAINT fk_dice_set_game
        FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE;

-- players
ALTER TABLE players ADD COLUMN game_id BIGINT;

ALTER TABLE players
    ADD CONSTRAINT fk_player_game
        FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE SET NULL;


-- --------------------------------------------------------
-- 4. TABLE game_cards
-- --------------------------------------------------------
CREATE TABLE game_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,
    owner_point_lvl1_id BIGINT,
    owner_point_lvl2_id BIGINT,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_game_card_board
        FOREIGN KEY (board_id)
            REFERENCES boards (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_game_card_card
        FOREIGN KEY (card_id)
            REFERENCES cards (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_game_card_owner_lvl1
        FOREIGN KEY (owner_point_lvl1_id)
            REFERENCES players (id)
            ON DELETE SET NULL,

    CONSTRAINT fk_game_card_owner_lvl2
        FOREIGN KEY (owner_point_lvl2_id)
            REFERENCES players (id)
            ON DELETE SET NULL
);

CREATE INDEX idx_games_current_player ON games (current_player_id);
CREATE INDEX idx_boards_game ON boards (game_id);
CREATE INDEX idx_game_cards_board ON game_cards (board_id);
CREATE INDEX idx_players_game ON players (game_id);