name: CI Dice Dice Baby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Backend Job
  build-back:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check Style & Compile
        run: |
          cd backend
          mvn spotless:check compile
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Test Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Frontend Job
  build-front:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Install & Lint
        run: |
          cd frontend 
          npm ci --legacy-peer-deps
          npm run lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Test Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max